config:
  # log_config:
  use_locks: &use_locks
    true
  log_config:
    log_config.ini
  satfire_config: &satfire_config
    !!python/object/apply:satfire.utils.read_config
      - /path/to/forest_fire_avhrr.yaml

work:
    - type: daemon
      name: listener
      components:
        - class: !!python/object:posttroll.listener.ListenerContainer
            topics:
              - /segment-hrpt-and-pps/
    - type: workflow
      name: satfire
      Workflow:
        - satfire.satfire_plugin.Satfire:
            config: *satfire_config
            use_lock: *use_locks
