config:
  # log_config:
  use_locks: &use_locks
    true
  log_config:
    log_config.ini
  fffsat_config: &fffsat_config
    !!python/object/apply:fffsat.utils.read_config
      - /path/to/forest_fire_avhrr.yaml

work:
    - type: daemon
      name: listener
      components:
        - class: !!python/object:posttroll.listener.ListenerContainer
            topics:
              - /segment-hrpt-and-pps/
    - type: workflow
      name: fffsat
      Workflow:
        - fffsat.fffsat_plugin.FFFsat:
            config: *fffsat_config
            use_lock: *use_locks
